name: auto-escape-special-unicode-characters-in-locales

on:
  pull_request:
  push:
    branches:
      - "trunk"

permissions:
  contents: read

jobs:
  auto-escape-special-unicode-characters-in-locales:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: trunk
    - name: escape ZWSP unexpectedly unescaped by GitLocalize
      run: "ZWSP=$'\\u200b'; grep -r -E \"$ZWSP\" webextensions/_locales | cut -d : -f 1 | uniq | xargs sed -i -r -e \"s/$ZWSP/\\\\\\\\u200b/g\" || echo 'there is no ZWSP'"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Escape special unicode characters in locales
        file_pattern: webextensions/_locales/*/*.json
        branch: trunk
 
