name: auto-fix-invalid-data-in-locales

on:
  pull_request:
  push:
    branches:
      - "trunk"

permissions:
  contents: read

jobs:
  auto-escape-special-unicode-characters-in-locales:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: trunk
    - name: escape ZWSP unexpectedly unescaped by GitLocalize
      run: |
        "ZWSP=$'\\u200b'; \
        grep -r -E \"$ZWSP\" webextensions/_locales | \
          cut -d : -f 1 | \
          uniq | \
          xargs sed -i -r -e \"s/$ZWSP/\\\\\\\\u200b/g\" || echo 'there is no ZWSP'"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Escape special unicode characters in locales
        file_pattern: webextensions/_locales/*/*.json
        branch: trunk

  auto-remove-blank-entry-in-locales:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: trunk
    - name: clear blank entries with no message by GitLocalize
      run: |
        ls "webextensions/_locales/*/*.json" | \
          while read path; do \
            if cat "$path" | \
                 jq '. | to_entries | .[] | select(.value.message | not) | .key' -r | \
                 grep . > /dev/null; then \
              cat "$path" | \
                jq 'to_entries[] | select(.value.message)' | \
                jq -s 'from_entries' \
                  > "$path.fixed"; \
              rm "$path"; \
              mv "$path.fixed" "$path"; \
            fi; \
          done
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Clear blank entries in locales
        file_pattern: webextensions/_locales/*/*.json
        branch: trunk
 
